In [1]:
import pandas as pd

In [13]:
#scrape data
string = "https://www.pro-football-reference.com/years/{}/fantasy.htm"
years = ["2017","2018","2019","2020","2021"]
data_dict = {}
for year in years:
    url = string.format(year)
    data = pd.read_html(url, header = 1)
    data_dict[year] = pd.DataFrame(data[0])
    
data_dict['2021'].dtypes

Rk         object
Player     object
Tm         object
FantPos    object
Age        object
G          object
GS         object
Cmp        object
Att        object
Yds        object
TD         object
Int        object
Att.1      object
Yds.1      object
Y/A        object
TD.1       object
Tgt        object
Rec        object
Yds.2      object
Y/R        object
TD.2       object
Fmb        object
FL         object
TD.3       object
2PM        object
2PP        object
FantPt     object
PPR        object
DKPt       object
FDPt       object
VBD        object
PosRank    object
OvRank     object
dtype: object

In [8]:
#clean NaN
for x,y in data_dict.items():
    data_dict[x] = data_dict[x].drop(data_dict[x][data_dict[x].Age == 'Age'].index)
    data_dict[x] = data_dict[x].dropna(subset = ['FantPos'])
    data_dict[x] = data_dict[x].fillna(0)
    print(data_dict[x].shape)

(536, 33)
(550, 33)
(558, 33)
(578, 33)
(596, 33)

In [11]:
data_dict['2018'].isna().sum()

Rk         0
Player     0
Tm         0
FantPos    0
Age        0
G          0
GS         0
Cmp        0
Att        0
Yds        0
TD         0
Int        0
Att.1      0
Yds.1      0
Y/A        0
TD.1       0
Tgt        0
Rec        0
Yds.2      0
Y/R        0
TD.2       0
Fmb        0
FL         0
TD.3       0
2PM        0
2PP        0
FantPt     0
PPR        0
DKPt       0
FDPt       0
VBD        0
PosRank    0
OvRank     0
dtype: int64

In [12]:
data_dict['2021'].head(100)

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,...,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Jonathan Taylor*+,IND,RB,22,17,17,0,0,0,...,20,0,0,333,373.1,381.1,353.1,187,1,1
1,2,Cooper Kupp*+,LAR,WR,28,17,17,0,1,0,...,16,1,0,295,439.5,442.5,367.0,173,1,2
2,3,Deebo Samuel*+,SFO,WR,25,16,15,1,2,24,...,14,0,0,262,339.0,347.0,300.5,140,2,3
3,4,Josh Allen,BUF,QB,25,17,17,409,646,4407,...,6,2,1,403,402.6,426.6,417.6,134,1,4
4,5,Austin Ekeler,LAC,RB,26,16,16,0,0,0,...,20,2,0,274,343.8,352.8,308.8,128,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,98,Darrell Henderson,LAR,RB,24,12,10,0,0,0,...,8,0,0,134,163.4,169.4,148.9,0,26,0
101,99,Justin Fields,CHI,QB,22,12,10,159,270,1870,...,2,0,0,127,126.8,147.8,136.8,0,31,0
102,100,Myles Gaskin,MIA,RB,24,17,10,0,0,0,...,7,0,0,125,173.6,180.6,149.1,0,28,0
103,101,Sony Michel,LAR,RB,26,17,7,0,0,0,...,5,0,0,125,146.3,153.3,135.8,0,27,0
104,102,Tony Pollard,DAL,RB,24,15,0,0,0,0,...,3,0,0,124,162.6,168.6,143.1,0,29,0